>P1;openfold
Structure: openfold: 2:A : 100:A ::::
DADVISFEASRGDLVVLDAIHDARFETEAGPGVYDIHSPRIPSEKEIEDRIYEILDKIDVKKVWINPDCG
LKTRGNDETWPSLEHLVAAAKAVRARLDK*
>P1;omegafold
Structure: omegafold: 2:A : 100:A ::::
DADVISFEASRGDLVVLDAIHDARFETEAGPGVYDIHSPRIPSEKEIEDRIYEILDKIDVKKVWINPDCG
LKTRGNDETWPSLEHLVAAAKAVRARLDK*

